export enum ACTION_TYPES {
    GET_BOARDS = '@@BOARD/GET_BOARDS',
    GET_BOARDS_PENDING = '@@BOARD/GET_BOARDS_PENDING',
    GET_BOARDS_FULFILLED = '@@BOARD/GET_BOARDS_FULFILLED',
    GET_BOARDS_REJECTED = '@@BOARD/GET_BOARDS_REJECTED',
    GET_BOARDS_ID = '@@BOARD/GET_BOARDS_ID'
}