export enum ACTION_TYPES {
    GET_LISTS = '@@LIST/GET_LISTS',
    GET_LISTS_PENDING = '@@LIST/GET_LISTS_PENDING',
    GET_LISTS_FULFILLED = '@@LIST/GET_LISTS_FULFILLED',
    GET_LISTS_REJECTED = '@@LIST/GET_LISTS_REJECTED'
}