export enum ACTION_TYPES {
    GET_PROFILE = '@@PROFILE/GET_PROFILE',
    GET_PROFILE_PENDING = '@@PROFILE/GET_PROFILE_PENDING',
    GET_PROFILE_FULFILLED = '@@PROFILE/GET_PROFILE_FULFILLED',
    GET_PROFILE_REJECTED = '@@PROFILE/GET_PROFILE_REJECTED',
}