export enum ACTION_TYPES {
    GET_CARDS = '@@CARDS/GET_CARDS',
    GET_CARDS_PENDING = '@@CARDS/GET_CARDS_PENDING',
    GET_CARDS_FULFILLED = '@@CARDS/GET_CARDS_FULFILLED',
    GET_CARDS_REJECTED = '@@CARDS/GET_CARDS_REJECTED',
}